apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - namespace.yaml
  - ../../base
  - dragonfly.yaml
  - hpa.yaml
patches:
  - target:
      kind: Deployment
      name: course-app-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Ingress
      name: course-app-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: course-app.prod.local
      - op: replace
        path: /spec/tls/0/hosts/0
        value: course-app.prod.local
images:
  - name: viktor1sss/course-app
    newName: viktor1sss/course-app
    newTag: viktor1sss/course-app:prod-v1.0.4 # {"$imagepolicy": "flux-system:course-app-prod"}
configMapGenerator:
  - name: course-app-config
    behavior: merge
    literals:
      - APP_REDIS_URL=redis://dragonfly:6379/0
