apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - namespace.yaml
  - ../../base
  - dragonfly.yaml
  - hpa.yaml
patches:
  - target:
      kind: Deployment
      name: course-app-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
configMapGenerator:
  - name: course-app-config
    behavior: merge
    literals:
      - APP_REDIS_URL=redis://dragonfly:6379/0
