apiVersion: v1
kind: ConfigMap
metadata:
  name: course-app-config
data:
  APP_STORE: "redis"
  APP_REDIS_URL: "redis://redis-course-app-svc:6379/0" # Default, can be patched in overlays
  APP_MESSAGE: "Base Config Message"
